### PR TITLE
Added Transaction Entity/Table

### PR DESCRIPTION
**Pull request by rohanbabbar04**
Issue: 10 

#### Short description of what this resolves:
Added the TransactionEntity class

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
I have also added the view model and livedata implementations in the gradle

**Comment by narayanaditya1007** [comment]
Fix the following problems and open PR again:
* Your PR is not according to the template, you shouldn't be using `#` before issue number.
* I think, you've forked the repo before OC started, you are 4 commits behind the main branch, first of all, fetch the upstream
* In the Transaction class, the primary key should be annotated nonNull 
* A constructor is missing, Add three constructors, 
                    * default one with no parameter
                    * one with all four parameters
                    * one with three parameters : `Date`,`Cost`,`Remark`
 * You don't need a setter for `TransactionId`, It would be auto-increment type, so remove the setter.
 * Other parameters except `TransactinID` would require setter for updating, so add setter for them.

**Comment by rohanbabbar04** [comment]
Do review @narayanaditya1007

**Comment by narayanaditya1007** [comment]
Good Job

**Pull request merged**
